### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by NerdTo** [Enaium-FabricMC/NoExpensive#14]
[12:00:57] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'noexpensive'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:25) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_310
        at cn.enaium.noexpensive.Config.<clinit>(Config.java:21) ~[NE-1.20-1.6.0.jar:?]
        at cn.enaium.noexpensive.NoExpensive.onInitialize(NoExpensive.java:50) ~[NE-1.20-1.6.0.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at cn.enaium.noexpensive.Config.<clinit>(Config.java:21) ~[NE-1.20-1.6.0.jar:?]
        at cn.enaium.noexpensive.NoExpensive.onInitialize(NoExpensive.java:50) ~[NE-1.20-1.6.0.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 8 more

**Comment by NerdTo** [comment]
1.20

**Comment by Enaium** [comment]
full log plz

**Comment by NerdTo** [comment]
ok

**Comment by NerdTo** [comment]
```
[12:00:36] [main/INFO]: Loading Minecraft 1.20 with Fabric Loader 0.14.21
[12:00:37] [main/INFO]: Loading 148 mods:
	- alternate-current 1.6.0
	- antixray 1.3.0
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- armor-stand-editor 2.1.1+1.20-rc1
	   |-- common-protection-api 1.0.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- player-data-api 0.2.2+1.19.3
	   |-- server_translations_api 2.0.0-beta.2+1.19.4-pre2
	   \-- sgui 1.2.2+1.20
	- audioplayer 1.20-1.5.2
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   \-- fabric-command-api-v2 2.2.11+b3afc78b27
	- banhammer 0.7.0+1.20
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- org_postgresql_postgresql 42.5.1
	   |-- org_xerial_sqlite-jdbc 3.40.0.0
	   |-- placeholder-api 2.1.1+1.20
	   \-- sgui 1.2.2+1.20
	- blockbot-discord 2.0.0-beta
	   |-- blockbot-api 1.0.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- placeholder-api 2.1.1+1.20
	- brewery 0.4.0+1.20-rc1
	   |-- net_objecthunter_exp4j 0.4.8
	   |-- placeholder-api 2.1.1+1.20
	   |-- server_translations_api 2.0.0-beta.2+1.19.4-pre2
	   \-- sgui 1.2.2+1.20
	- c2me 0.2.0+alpha.10.85
	   |-- c2me-base 0.2.0+alpha.10.85
	   |-- c2me-client-uncapvd 0.2.0+alpha.10.85
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.10.85
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.10.85
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.10.85
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.10.85
	   |-- c2me-notickvd 0.2.0+alpha.10.85
	   |-- c2me-opts-allocs 0.2.0+alpha.10.85
	   |-- c2me-opts-chunk-access 0.2.0+alpha.10.85
	   |-- c2me-opts-chunkio 0.2.0+alpha.10.85
	   |-- c2me-opts-math 0.2.0+alpha.10.85
	   |-- c2me-opts-scheduling 0.2.0+alpha.10.85
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.10.85
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.10.85
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.10.85
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.10.85
	   |-- c2me-server-utils 0.2.0+alpha.10.85
	   |-- c2me-threading-chunkio 0.2.0+alpha.10.85
	   |-- c2me-threading-lighting 0.2.0+alpha.10.85
	   |-- c2me-threading-worldgen 0.2.0+alpha.10.85
	   |-- com_ibm_async_asyncutil 0.1.0
	   \-- org_threadly_threadly 7.0
	- carpet 1.4.112+v230608
	- carpet-tis-addition 1.47.0
	   \-- conditional-mixin 0.3.2
	- collective 6.57
	- easyauth 3.0.0-16
	   |-- at_favre_lib_bcrypt 0.9.0
	   |-- at_favre_lib_bytes 1.5.0
	   |-- com_mysql_mysql-connector-j 8.0.33
	   |-- de_mkammerer_argon2-jvm 2.11
	   |-- de_mkammerer_argon2-jvm-nolibs 2.11
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- net_java_dev_jna_jna 5.12.1
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_mongodb_bson 4.7.2
	   |-- org_mongodb_mongodb-driver-core 4.7.2
	   |-- org_mongodb_mongodb-driver-sync 4.7.2
	   |-- placeholder-api 2.1.1+1.20
	   \-- server_translations_api 2.0.0-beta.2+1.19.4-pre2
	- easywhitelist 1.0.1
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- fabric-api 0.83.0+1.20
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c927
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b27
	   |-- fabric-block-api-v1 1.0.9+e022e5d127
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b27
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b27
	   |-- fabric-command-api-v1 1.2.32+f71b366f27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-commands-v0 0.2.49+df3654b327
	   |-- fabric-containers-v0 0.1.61+df3654b327
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b27
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b27
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe27
	   |-- fabric-data-generation-api-v1 12.1.10+b3afc78b27
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b27
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b27
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b27
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b327
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a27
	   |-- fabric-item-api-v1 2.1.26+b3afc78b27
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-keybindings-v0 0.2.34+df3654b327
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b27
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c627
	   |-- fabric-message-api-v1 5.1.6+b3afc78b27
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b27
	   |-- fabric-models-v0 0.3.35+b3afc78b27
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b27
	   |-- fabric-networking-v0 0.3.48+df3654b327
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b27
	   |-- fabric-particles-v1 1.0.28+b3afc78b27
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b27
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b27
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b27
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b27
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b327
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b27
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b27
	   |-- fabric-rendering-v0 1.1.47+df3654b327
	   |-- fabric-rendering-v1 3.0.6+b3afc78b27
	   |-- fabric-resource-conditions-api-v1 2.3.4+b3afc78b27
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b27
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b27
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b27
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b27
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b27
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.21
	- fabrictailor 2.1.2
	   |-- config2brigadier 1.2.3
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- fastload 3.4.0
	   |-- fastload-119-0-1-2-compat 3.4.0
	   |-- fastload-1193-compat 3.4.0
	   |-- fastload-1194-compat 3.4.0
	   \-- fastload_fapi_forward 1.0.2
	- ferritecore 6.0.0
	- geyser-fabric 2.1.1-SNAPSHOT
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- invisibleframes 1.1.0
	- java 17
	- justmobheads 7.1
	- ledger 1.2.8
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- server_translations_api 2.0.0-beta.2+1.19.4-pre2
	- lithium 0.11.2
	- melius-vanish 1.4.1+1.20-rc1
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-message-api-v1 5.1.6+b3afc78b27
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	   |-- placeholder-api 2.1.1+1.20
	   |-- player-data-api 0.2.2+1.19.3
	   \-- server_translations_api 2.0.0-beta.2+1.19.4-pre2
	- minecraft 1.20
	- noexpensive 1.20-1.6.0
	- polymer-bundled 0.5.0-rc.3+1.20
	   |-- polymer-autohost 0.5.0-rc.3+1.20
	   |-- polymer-blocks 0.5.0-rc.3+1.20
	   |-- polymer-common 0.5.0-rc.3+1.20
	   |    \-- packet_tweaker 0.4.0+1.19.4
	   |-- polymer-core 0.5.0-rc.3+1.20
	   |    |-- polymer-networking 0.5.0-rc.3+1.20
	   |    |    \-- polymer-common 0.5.0-rc.3+1.20
	   |    |         \-- packet_tweaker 0.4.0+1.19.4
	   |    \-- polymer-registry-sync-manipulator 0.5.0-rc.3+1.20
	   |-- polymer-resource-pack 0.5.0-rc.3+1.20
	   |    \-- polymer-common 0.5.0-rc.3+1.20
	   |         \-- packet_tweaker 0.4.0+1.19.4
	   \-- polymer-virtual-entity 0.5.0-rc.3+1.20
	        \-- polymer-common 0.5.0-rc.3+1.20
	             \-- packet_tweaker 0.4.0+1.19.4
	- servercore 1.3.6+1.20
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- placeholder-api 2.1.1+1.20
	- smoothboot 1.19.4-1.7.0
	- spark 1.10.41
	- styledplayerlist 3.1.0+1.20
	   |-- placeholder-api 2.1.1+1.20
	   |-- player-data-api 0.2.2+1.19.3
	   \-- predicate-api 0.1.2+1.20
	- vcinteraction 1.20-1.0.3
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b27
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	- villagerconfig 4.0.1+1.20-rc1
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |-- config2brigadier 1.2.3
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	   |-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b27
	   \-- fiber 0.23.0-2
	- vmp 0.2.0+beta.7.93
	- voicechat 1.20-2.4.9
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b27
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d27
[12:00:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/F:/ATLauncher/servers/Minecraft120withFabric/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[12:00:38] [main/INFO]: Compatibility level set to JAVA_16
[12:00:38] [main/INFO]: Compatibility level set to JAVA_17
[12:00:38] [main/INFO]: Initializing com.ishland.c2me.base.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.fixes.chunkio.threading_issues.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.fixes.general.threading_issues.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.threading_issues.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.vanilla_bugs.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.notickvd.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.opts.allocs.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.opts.chunk_access.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.opts.chunkio.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.opts.math.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.opts.scheduling.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.general.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.vanilla.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunk_serializer.mixin
[12:00:39] [main/INFO]: Disabling com.ishland.c2me.rewrites.chunk_serializer.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunkio.mixin
[12:00:39] [main/INFO]: Disabling com.ishland.c2me.rewrites.chunkio.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.server.utils.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.threading.chunkio.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.threading.lighting.mixin
[12:00:39] [main/INFO]: Initializing com.ishland.c2me.threading.worldgen.mixin
[12:00:39] [main/INFO]: Disabling com.ishland.c2me.threading.worldgen.mixin
[12:00:39] [main/WARN]: Reference map 'Fastload-1.19.4-Extension-refmap.json' for fastload-1194-compat.mixins.json could not be read. If this is a development environment you can ignore this message
[12:00:39] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 3 override(s) found
[12:00:39] [main/INFO]: Successfully started async appender with [ServerGuiConsole, SysOut, File]
[12:00:40] [main/WARN]: Mixin malte0811.ferritecore.mixin.threaddetec.PalettedContainerMixin is disabled automatically as lithium is installed
[12:00:40] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[12:00:40] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
[12:00:40] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [c2me, vmp]) disables it and children
[12:00:40] [main/WARN]: Error loading class: net/minecraft/class_471 (java.lang.ClassNotFoundException: net/minecraft/class_471)
[12:00:40] [main/WARN]: @Mixin target net.minecraft.class_471 was not found noexpensive.mixins.json:AnvilScreenMixin from mod noexpensive
[12:00:41] [main/INFO]: Smooth Boot config initialized
[12:00:50] [main/WARN]: Method overwrite conflict for getConnection in fabric-networking-api-v1.mixins.json:accessor.ServerPlayNetworkHandlerAccessor from mod fabric-networking-api-v1, previously written by carpet.mixins.ServerGamePacketListenerImpl_coreMixin. Skipping method.
[12:00:53] [main/INFO]: Initializing
[12:00:55] [main/ERROR]: io.github.quiltservertools.blockbotdiscord.libs.com.uchuhimo.konf.UnsetValueException: item guild is unset
[12:00:55] [main/FATAL]: Config invalid. Disabling mod...
[12:00:55] [main/INFO]: Loading Collective version 6.57.
[12:00:55] [main/INFO]: Loaded C2B lib.
[12:00:55] [main/INFO]: [EasyAuth]: EasyAuth mod by samo_lego, NikitaCartes.
[12:00:56] [TISCM Mapping/INFO]: Yarn mapping file yarn-1.20+build.1-v2.tiny loaded
[12:00:56] [main/INFO]: [EasyWhitelist] Whitelist is now name-based.
[12:00:56] [main/INFO]: Загрузка расширений...
[12:00:56] [main/INFO]: Загружено расширений: 0
[12:00:57] [main/INFO]: [STDOUT]: Hello NoExpensive world!
[12:00:57] [main/INFO]: [ServerCore] Loaded V1.3.6+1.20!
[12:00:57] [main/INFO]: Compatibility version 17
[12:00:57] [main/INFO]: Loading plugins
[12:00:57] [main/INFO]: Loaded 2 plugin(s)
[12:00:57] [main/INFO]: Initializing plugins
[12:00:57] [main/INFO]: Initialized 2 plugin(s)
[12:00:57] [main/INFO]: Registering events for audioplayer
[12:00:57] [main/INFO]: Registering events for vcinteraction
[12:00:57] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'noexpensive'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:25) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_310
	at cn.enaium.noexpensive.Config.<clinit>(Config.java:21) ~[NE-1.20-1.6.0.jar:?]
	at cn.enaium.noexpensive.NoExpensive.onInitialize(NoExpensive.java:50) ~[NE-1.20-1.6.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cn.enaium.noexpensive.Config.<clinit>(Config.java:21) ~[NE-1.20-1.6.0.jar:?]
	at cn.enaium.noexpensive.NoExpensive.onInitialize(NoExpensive.java:50) ~[NE-1.20-1.6.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more
```

**Comment by Enaium** [comment]
Try to use only `fabric-api` and `noexpensive`, these mods may be incompatible.

**Comment by Enaium** [comment]
Are you running the game in a server environment?

**Comment by NerdTo** [comment]
I can check this on the VM in Sweden, but I don't think it makes any difference

**Comment by Enaium** [comment]
> I can check this on the VM in Sweden, but I don't think it makes any difference

This issue occurs if you are running in a server environment, I will fix this issue.

**Comment by NerdTo** [comment]
![image](https://github.com/Enaium-FabricMC/NoExpensive/assets/116191734/994ec2a8-28c7-4f03-85f5-3af9fcfddad7)
hm

**Comment by Enaium** [comment]
> ![image](https://user-images.githubusercontent.com/116191734/244647200-994ec2a8-28c7-4f03-85f5-3af9fcfddad7.png) hm

I am adding many new features in the new version, I forgot in a server environment will be many issues.

**Comment by NerdTo** [comment]
ok

**Comment by Enaium** [comment]
Fixed
